parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: '3306'
    database_name: maloshabitos
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: c792aaef338204910b7cebab2c848210710
    database_path: null
